[tool.poetry]
name = "framework-practice"
version = "0.1.0"
description = ""
authors = ["Namgyu-Youn <yynk2012@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
